url: https://y7kim.github.io
baseurl:

# Site settings
title: FRNKDNNY — Graphic Design
email: frnkdnny@gmail.com
description: "Graphic Design"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 12, 239, 212, .50
  secondary: 12, 239, 212, 1
  secondary-dark: 363636

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://www.facebook.com/FRNKDNNY
  - title: twitter
    url: http://twitter.com/frnkdnny
  - title: dribbble
    url: http://dribbble.com/frnkdnny
  - title: behance
    url: http://www.behance.net/frnkdnny
  - title: linkedin
    url: http://www.linkedin.com/in/frnkdnny

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
